Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Classes\\Result",
            "name": "Result",
            "summary": "",
            "url": "classes/App-Classes-Result.html"
        },                {
            "fqsen": "\\App\\Classes\\Result\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Classes-Result.html#property_username"
        },                {
            "fqsen": "\\App\\Classes\\Result\u003A\u003A\u0024rank",
            "name": "rank",
            "summary": "",
            "url": "classes/App-Classes-Result.html#property_rank"
        },                {
            "fqsen": "\\App\\Classes\\Result\u003A\u003A\u0024score",
            "name": "score",
            "summary": "",
            "url": "classes/App-Classes-Result.html#property_score"
        },                {
            "fqsen": "\\App\\Classes\\Result\u003A\u003A\u0024result",
            "name": "result",
            "summary": "",
            "url": "classes/App-Classes-Result.html#property_result"
        },                {
            "fqsen": "\\App\\Classes\\Result\u003A\u003A\u0024solved",
            "name": "solved",
            "summary": "",
            "url": "classes/App-Classes-Result.html#property_solved"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController",
            "name": "ContestsController",
            "summary": "Class\u0020ContestsController",
            "url": "classes/App-Controller-ContestsController.html"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AcontestList\u0028\u0029",
            "name": "contestList",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_contestList"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Aupcoming\u0028\u0029",
            "name": "upcoming",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_upcoming"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Acontest\u0028\u0029",
            "name": "contest",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_contest"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Acontest_registration\u0028\u0029",
            "name": "contest_registration",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_contest_registration"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AupdateSubmissions\u0028\u0029",
            "name": "updateSubmissions",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_updateSubmissions"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AgetSubmissions\u0028\u0029",
            "name": "getSubmissions",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_getSubmissions"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Aget_all_submissions\u0028\u0029",
            "name": "get_all_submissions",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_get_all_submissions"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Aproblem\u0028\u0029",
            "name": "problem",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_problem"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Asubmit\u0028\u0029",
            "name": "submit",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_submit"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AprocessSubmit\u0028\u0029",
            "name": "processSubmit",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_processSubmit"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Asolution\u0028\u0029",
            "name": "solution",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_solution"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Ascoreboard\u0028\u0029",
            "name": "scoreboard",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_scoreboard"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Amy_submissions\u0028\u0029",
            "name": "my_submissions",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_my_submissions"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_create"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AvalidateDate\u0028\u0029",
            "name": "validateDate",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_validateDate"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AprocessCreate\u0028\u0029",
            "name": "processCreate",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_processCreate"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AmyContests\u0028\u0029",
            "name": "myContests",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_myContests"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AaddProblem\u0028\u0029",
            "name": "addProblem",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_addProblem"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AcheckLetter\u0028\u0029",
            "name": "checkLetter",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_checkLetter"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AeditProblem\u0028\u0029",
            "name": "editProblem",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_editProblem"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003AprocessEditProblem\u0028\u0029",
            "name": "processEditProblem",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_processEditProblem"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#method_publish"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003A\u0024em",
            "name": "em",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#property_em"
        },                {
            "fqsen": "\\App\\Controller\\ContestsController\u003A\u003A\u0024j",
            "name": "j",
            "summary": "",
            "url": "classes/App-Controller-ContestsController.html#property_j"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController",
            "name": "CoursesController",
            "summary": "Class\u0020CoursesController",
            "url": "classes/App-Controller-CoursesController.html"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Acourses\u0028\u0029",
            "name": "courses",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_courses"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Asorting\u0028\u0029",
            "name": "sorting",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_sorting"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Acomplexity\u0028\u0029",
            "name": "complexity",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_complexity"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Ads\u0028\u0029",
            "name": "ds",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_ds"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Atree\u0028\u0029",
            "name": "tree",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_tree"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Adp\u0028\u0029",
            "name": "dp",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_dp"
        },                {
            "fqsen": "\\App\\Controller\\CoursesController\u003A\u003Agraph\u0028\u0029",
            "name": "graph",
            "summary": "",
            "url": "classes/App-Controller-CoursesController.html#method_graph"
        },                {
            "fqsen": "\\App\\Controller\\HomeController",
            "name": "HomeController",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Asignup\u0028\u0029",
            "name": "signup",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html#method_signup"
        },                {
            "fqsen": "\\App\\Controller\\HomeController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/App-Controller-HomeController.html#method_register"
        },                {
            "fqsen": "\\App\\Controller\\ProblemsController",
            "name": "ProblemsController",
            "summary": "",
            "url": "classes/App-Controller-ProblemsController.html"
        },                {
            "fqsen": "\\App\\Controller\\ProblemsController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-ProblemsController.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\ProblemsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-ProblemsController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\ProblemsController\u003A\u003A\u0024em",
            "name": "em",
            "summary": "",
            "url": "classes/App-Controller-ProblemsController.html#property_em"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controller\\ToolsController",
            "name": "ToolsController",
            "summary": "",
            "url": "classes/App-Controller-ToolsController.html"
        },                {
            "fqsen": "\\App\\Controller\\ToolsController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-ToolsController.html#method_index"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixture",
            "name": "AppFixture",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixture.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixture\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-DataFixtures-AppFixture.html#method_load"
        },                {
            "fqsen": "\\App\\Entity\\Contest",
            "name": "Contest",
            "summary": "",
            "url": "classes/App-Entity-Contest.html"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getDuration"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AsetDuration\u0028\u0029",
            "name": "setDuration",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_setDuration"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetProblems\u0028\u0029",
            "name": "getProblems",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getProblems"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetProblem\u0028\u0029",
            "name": "getProblem",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getProblem"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AaddProblem\u0028\u0029",
            "name": "addProblem",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_addProblem"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AremoveProblem\u0028\u0029",
            "name": "removeProblem",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_removeProblem"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetIsPublished\u0028\u0029",
            "name": "getIsPublished",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getIsPublished"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AsetIsPublished\u0028\u0029",
            "name": "setIsPublished",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_setIsPublished"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetCreator\u0028\u0029",
            "name": "getCreator",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getCreator"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AsetCreator\u0028\u0029",
            "name": "setCreator",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_setCreator"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetParticipants\u0028\u0029",
            "name": "getParticipants",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getParticipants"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AaddParticipant\u0028\u0029",
            "name": "addParticipant",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_addParticipant"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AremoveParticipant\u0028\u0029",
            "name": "removeParticipant",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_removeParticipant"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getStatus"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AgetStartDate\u0028\u0029",
            "name": "getStartDate",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_getStartDate"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003AsetStartDate\u0028\u0029",
            "name": "setStartDate",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_setStartDate"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003Aallowed_inside_contest\u0028\u0029",
            "name": "allowed_inside_contest",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#method_allowed_inside_contest"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024duration",
            "name": "duration",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_duration"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024problems",
            "name": "problems",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_problems"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024isPublished",
            "name": "isPublished",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_isPublished"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024creator",
            "name": "creator",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_creator"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024participants",
            "name": "participants",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_participants"
        },                {
            "fqsen": "\\App\\Entity\\Contest\u003A\u003A\u0024start_date",
            "name": "start_date",
            "summary": "",
            "url": "classes/App-Entity-Contest.html#property_start_date"
        },                {
            "fqsen": "\\App\\Entity\\Input",
            "name": "Input",
            "summary": "",
            "url": "classes/App-Entity-Input.html"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Input.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003AgetInput\u0028\u0029",
            "name": "getInput",
            "summary": "",
            "url": "classes/App-Entity-Input.html#method_getInput"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003AsetInput\u0028\u0029",
            "name": "setInput",
            "summary": "",
            "url": "classes/App-Entity-Input.html#method_setInput"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "",
            "url": "classes/App-Entity-Input.html#method_getOutput"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003AsetOutput\u0028\u0029",
            "name": "setOutput",
            "summary": "",
            "url": "classes/App-Entity-Input.html#method_setOutput"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Input.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003A\u0024input",
            "name": "input",
            "summary": "",
            "url": "classes/App-Entity-Input.html#property_input"
        },                {
            "fqsen": "\\App\\Entity\\Input\u003A\u003A\u0024output",
            "name": "output",
            "summary": "",
            "url": "classes/App-Entity-Input.html#property_output"
        },                {
            "fqsen": "\\App\\Entity\\Problem",
            "name": "Problem",
            "summary": "",
            "url": "classes/App-Entity-Problem.html"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetLetter\u0028\u0029",
            "name": "getLetter",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getLetter"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetLetter\u0028\u0029",
            "name": "setLetter",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setLetter"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetStatement\u0028\u0029",
            "name": "getStatement",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getStatement"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetStatement\u0028\u0029",
            "name": "setStatement",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setStatement"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetInputSpec\u0028\u0029",
            "name": "getInputSpec",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getInputSpec"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetInputSpec\u0028\u0029",
            "name": "setInputSpec",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setInputSpec"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetOutputSpec\u0028\u0029",
            "name": "getOutputSpec",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getOutputSpec"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetOutputSpec\u0028\u0029",
            "name": "setOutputSpec",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setOutputSpec"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetValidator\u0028\u0029",
            "name": "getValidator",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getValidator"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetValidator\u0028\u0029",
            "name": "setValidator",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setValidator"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetContest\u0028\u0029",
            "name": "getContest",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getContest"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetContest\u0028\u0029",
            "name": "setContest",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setContest"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getTags"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AaddTag\u0028\u0029",
            "name": "addTag",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_addTag"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AremoveTag\u0028\u0029",
            "name": "removeTag",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_removeTag"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetSampleIn\u0028\u0029",
            "name": "getSampleIn",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getSampleIn"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AaddSampleIn\u0028\u0029",
            "name": "addSampleIn",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_addSampleIn"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AremoveSampleIn\u0028\u0029",
            "name": "removeSampleIn",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_removeSampleIn"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetSolution\u0028\u0029",
            "name": "getSolution",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getSolution"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetSolution\u0028\u0029",
            "name": "setSolution",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setSolution"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetProof\u0028\u0029",
            "name": "getProof",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getProof"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetProof\u0028\u0029",
            "name": "setProof",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setProof"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetPoints\u0028\u0029",
            "name": "getPoints",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getPoints"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetPoints\u0028\u0029",
            "name": "setPoints",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setPoints"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetSubmissions\u0028\u0029",
            "name": "getSubmissions",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getSubmissions"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AaddSubmission\u0028\u0029",
            "name": "addSubmission",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_addSubmission"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AremoveSubmission\u0028\u0029",
            "name": "removeSubmission",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_removeSubmission"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetTimeLimit\u0028\u0029",
            "name": "getTimeLimit",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getTimeLimit"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetTimeLimit\u0028\u0029",
            "name": "setTimeLimit",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setTimeLimit"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AgetInput\u0028\u0029",
            "name": "getInput",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_getInput"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003AsetInput\u0028\u0029",
            "name": "setInput",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#method_setInput"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024Letter",
            "name": "Letter",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_Letter"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024statement",
            "name": "statement",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_statement"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024inputSpec",
            "name": "inputSpec",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_inputSpec"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024outputSpec",
            "name": "outputSpec",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_outputSpec"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_validator"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024contest",
            "name": "contest",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_contest"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_tags"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024sampleIn",
            "name": "sampleIn",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_sampleIn"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024solution",
            "name": "solution",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_solution"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024proof",
            "name": "proof",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_proof"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024points",
            "name": "points",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_points"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024submissions",
            "name": "submissions",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_submissions"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024timeLimit",
            "name": "timeLimit",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_timeLimit"
        },                {
            "fqsen": "\\App\\Entity\\Problem\u003A\u003A\u0024input",
            "name": "input",
            "summary": "",
            "url": "classes/App-Entity-Problem.html#property_input"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput",
            "name": "SampleInput",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AgetInput\u0028\u0029",
            "name": "getInput",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_getInput"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AsetInput\u0028\u0029",
            "name": "setInput",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_setInput"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_getOutput"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AsetOutput\u0028\u0029",
            "name": "setOutput",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_setOutput"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AgetProblem\u0028\u0029",
            "name": "getProblem",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_getProblem"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003AsetProblem\u0028\u0029",
            "name": "setProblem",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#method_setProblem"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003A\u0024input",
            "name": "input",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#property_input"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003A\u0024output",
            "name": "output",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#property_output"
        },                {
            "fqsen": "\\App\\Entity\\SampleInput\u003A\u003A\u0024problem",
            "name": "problem",
            "summary": "",
            "url": "classes/App-Entity-SampleInput.html#property_problem"
        },                {
            "fqsen": "\\App\\Entity\\Status",
            "name": "Status",
            "summary": "",
            "url": "classes/App-Entity-Status.html"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AgetSubmissions\u0028\u0029",
            "name": "getSubmissions",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_getSubmissions"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AaddSubmission\u0028\u0029",
            "name": "addSubmission",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_addSubmission"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AremoveSubmission\u0028\u0029",
            "name": "removeSubmission",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_removeSubmission"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AgetCode\u0028\u0029",
            "name": "getCode",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_getCode"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003AsetCode\u0028\u0029",
            "name": "setCode",
            "summary": "",
            "url": "classes/App-Entity-Status.html#method_setCode"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Status.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Entity-Status.html#property_description"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003A\u0024submissions",
            "name": "submissions",
            "summary": "",
            "url": "classes/App-Entity-Status.html#property_submissions"
        },                {
            "fqsen": "\\App\\Entity\\Status\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/App-Entity-Status.html#property_code"
        },                {
            "fqsen": "\\App\\Entity\\Submission",
            "name": "Submission",
            "summary": "",
            "url": "classes/App-Entity-Submission.html"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetProblem\u0028\u0029",
            "name": "getProblem",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getProblem"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetProblem\u0028\u0029",
            "name": "setProblem",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setProblem"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetCode\u0028\u0029",
            "name": "getCode",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getCode"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetCode\u0028\u0029",
            "name": "setCode",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setCode"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetLanguage\u0028\u0029",
            "name": "getLanguage",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getLanguage"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetLanguage\u0028\u0029",
            "name": "setLanguage",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setLanguage"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getUser"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setUser"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getToken"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetToken\u0028\u0029",
            "name": "setToken",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setToken"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getStatus"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetStatus\u0028\u0029",
            "name": "setStatus",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setStatus"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AgetInContest\u0028\u0029",
            "name": "getInContest",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_getInContest"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003AsetInContest\u0028\u0029",
            "name": "setInContest",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#method_setInContest"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024problem",
            "name": "problem",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_problem"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_code"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024language",
            "name": "language",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_language"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_user"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_token"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_status"
        },                {
            "fqsen": "\\App\\Entity\\Submission\u003A\u003A\u0024inContest",
            "name": "inContest",
            "summary": "",
            "url": "classes/App-Entity-Submission.html#property_inContest"
        },                {
            "fqsen": "\\App\\Entity\\Tag",
            "name": "Tag",
            "summary": "",
            "url": "classes/App-Entity-Tag.html"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003AgetProblems\u0028\u0029",
            "name": "getProblems",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method_getProblems"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003AaddProblem\u0028\u0029",
            "name": "addProblem",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method_addProblem"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003AremoveProblem\u0028\u0029",
            "name": "removeProblem",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#method_removeProblem"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Tag\u003A\u003A\u0024problems",
            "name": "problems",
            "summary": "",
            "url": "classes/App-Entity-Tag.html#property_problems"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-User.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "A\u0020visual\u0020identifier\u0020that\u0020represents\u0020this\u0020user.",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetSalt\u0028\u0029",
            "name": "getSalt",
            "summary": "Returning\u0020a\u0020salt\u0020is\u0020only\u0020needed,\u0020if\u0020you\u0020are\u0020not\u0020using\u0020a\u0020modern\nhashing\u0020algorithm\u0020\u0028e.g.\u0020bcrypt\u0020or\u0020sodium\u0029\u0020in\u0020your\u0020security.yaml.",
            "url": "classes/App-Entity-User.html#method_getSalt"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetFullName\u0028\u0029",
            "name": "getFullName",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getFullName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetFullName\u0028\u0029",
            "name": "setFullName",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setFullName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetCreatedContests\u0028\u0029",
            "name": "getCreatedContests",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getCreatedContests"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddCreatedContest\u0028\u0029",
            "name": "addCreatedContest",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_addCreatedContest"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveCreatedContest\u0028\u0029",
            "name": "removeCreatedContest",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_removeCreatedContest"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetContests\u0028\u0029",
            "name": "getContests",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getContests"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddContest\u0028\u0029",
            "name": "addContest",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_addContest"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveContest\u0028\u0029",
            "name": "removeContest",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_removeContest"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetSubmissions\u0028\u0029",
            "name": "getSubmissions",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_getSubmissions"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddSubmission\u0028\u0029",
            "name": "addSubmission",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_addSubmission"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveSubmission\u0028\u0029",
            "name": "removeSubmission",
            "summary": "",
            "url": "classes/App-Entity-User.html#method_removeSubmission"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024fullName",
            "name": "fullName",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_fullName"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024createdContests",
            "name": "createdContests",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_createdContests"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024contests",
            "name": "contests",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_contests"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024submissions",
            "name": "submissions",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_submissions"
        },                {
            "fqsen": "\\App\\Form\\UserType",
            "name": "UserType",
            "summary": "",
            "url": "classes/App-Form-UserType.html"
        },                {
            "fqsen": "\\App\\Form\\UserType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "",
            "url": "classes/App-Form-UserType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\UserType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-UserType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureContainer\u0028\u0029",
            "name": "configureContainer",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureContainer"
        },                {
            "fqsen": "\\App\\Kernel\u003A\u003AconfigureRoutes\u0028\u0029",
            "name": "configureRoutes",
            "summary": "",
            "url": "classes/App-Kernel.html#method_configureRoutes"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository",
            "name": "ContestRepository",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository\u003A\u003AfindByTitle\u0028\u0029",
            "name": "findByTitle",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html#method_findByTitle"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository\u003A\u003Afindupcoming\u0028\u0029",
            "name": "findupcoming",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html#method_findupcoming"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository\u003A\u003Afindrecent\u0028\u0029",
            "name": "findrecent",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html#method_findrecent"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository\u003A\u003AfindAllOrderedbyDate\u0028\u0029",
            "name": "findAllOrderedbyDate",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html#method_findAllOrderedbyDate"
        },                {
            "fqsen": "\\App\\Repository\\ContestRepository\u003A\u003AfindAllDate\u0028\u0029",
            "name": "findAllDate",
            "summary": "",
            "url": "classes/App-Repository-ContestRepository.html#method_findAllDate"
        },                {
            "fqsen": "\\App\\Repository\\InputRepository",
            "name": "InputRepository",
            "summary": "",
            "url": "classes/App-Repository-InputRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\InputRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-InputRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ProblemRepository",
            "name": "ProblemRepository",
            "summary": "",
            "url": "classes/App-Repository-ProblemRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\ProblemRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-ProblemRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ProblemRepository\u003A\u003AfindByTitle\u0028\u0029",
            "name": "findByTitle",
            "summary": "",
            "url": "classes/App-Repository-ProblemRepository.html#method_findByTitle"
        },                {
            "fqsen": "\\App\\Repository\\ProblemRepository\u003A\u003AfindByTagsQuery\u0028\u0029",
            "name": "findByTagsQuery",
            "summary": "",
            "url": "classes/App-Repository-ProblemRepository.html#method_findByTagsQuery"
        },                {
            "fqsen": "\\App\\Repository\\ProblemRepository\u003A\u003AfindByTitleAndTags\u0028\u0029",
            "name": "findByTitleAndTags",
            "summary": "",
            "url": "classes/App-Repository-ProblemRepository.html#method_findByTitleAndTags"
        },                {
            "fqsen": "\\App\\Repository\\ProblemRepository\u003A\u003AfindByTags\u0028\u0029",
            "name": "findByTags",
            "summary": "",
            "url": "classes/App-Repository-ProblemRepository.html#method_findByTags"
        },                {
            "fqsen": "\\App\\Repository\\SampleInputRepository",
            "name": "SampleInputRepository",
            "summary": "",
            "url": "classes/App-Repository-SampleInputRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\SampleInputRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-SampleInputRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\StatusRepository",
            "name": "StatusRepository",
            "summary": "",
            "url": "classes/App-Repository-StatusRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\StatusRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-StatusRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\SubmissionRepository",
            "name": "SubmissionRepository",
            "summary": "",
            "url": "classes/App-Repository-SubmissionRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\SubmissionRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-SubmissionRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\TagRepository",
            "name": "TagRepository",
            "summary": "",
            "url": "classes/App-Repository-TagRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\TagRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-TagRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AupgradePassword\u0028\u0029",
            "name": "upgradePassword",
            "summary": "Used\u0020to\u0020upgrade\u0020\u0028rehash\u0029\u0020the\u0020user\u0027s\u0020password\u0020automatically\u0020over\u0020time.",
            "url": "classes/App-Repository-UserRepository.html#method_upgradePassword"
        },                {
            "fqsen": "\\App\\Repository\\UsersRepository",
            "name": "UsersRepository",
            "summary": "",
            "url": "classes/App-Repository-UsersRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UsersRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Repository-UsersRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\ContestLoginException",
            "name": "ContestLoginException",
            "summary": "",
            "url": "classes/App-Security-ContestLoginException.html"
        },                {
            "fqsen": "\\App\\Security\\ContestLoginException\u003A\u003AgetMessageKey\u0028\u0029",
            "name": "getMessageKey",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/App-Security-ContestLoginException.html#method_getMessageKey"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator",
            "name": "LoginFormAuthenticator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_supports"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetCredentials\u0028\u0029",
            "name": "getCredentials",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getCredentials"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getUser"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AcheckCredentials\u0028\u0029",
            "name": "checkCredentials",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_checkCredentials"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Used\u0020to\u0020upgrade\u0020\u0028rehash\u0029\u0020the\u0020user\u0027s\u0020password\u0020automatically\u0020over\u0020time.",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024csrfTokenManager",
            "name": "csrfTokenManager",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_csrfTokenManager"
        },                {
            "fqsen": "\\App\\Security\\LoginFormAuthenticator\u003A\u003A\u0024passwordEncoder",
            "name": "passwordEncoder",
            "summary": "",
            "url": "classes/App-Security-LoginFormAuthenticator.html#property_passwordEncoder"
        },                {
            "fqsen": "\\App\\Service\\Judge",
            "name": "Judge",
            "summary": "",
            "url": "classes/App-Service-Judge.html"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Service-Judge.html#method___construct"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003Asubmit\u0028\u0029",
            "name": "submit",
            "summary": "",
            "url": "classes/App-Service-Judge.html#method_submit"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003AgetSubmission\u0028\u0029",
            "name": "getSubmission",
            "summary": "",
            "url": "classes/App-Service-Judge.html#method_getSubmission"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/App-Service-Judge.html#property_client"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/App-Service-Judge.html#property_url"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/App-Service-Judge.html#property_key"
        },                {
            "fqsen": "\\App\\Service\\Judge\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/App-Service-Judge.html#property_host"
        },                {
            "fqsen": "\\App\\Twig\\DurationHelperExtension",
            "name": "DurationHelperExtension",
            "summary": "",
            "url": "classes/App-Twig-DurationHelperExtension.html"
        },                {
            "fqsen": "\\App\\Twig\\DurationHelperExtension\u003A\u003AgetFilters\u0028\u0029",
            "name": "getFilters",
            "summary": "",
            "url": "classes/App-Twig-DurationHelperExtension.html#method_getFilters"
        },                {
            "fqsen": "\\App\\Twig\\DurationHelperExtension\u003A\u003Aduration_helper\u0028\u0029",
            "name": "duration_helper",
            "summary": "",
            "url": "classes/App-Twig-DurationHelperExtension.html#method_duration_helper"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Classes",
            "name": "Classes",
            "summary": "",
            "url": "namespaces/app-classes.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        },                {
            "fqsen": "\\App\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/app-service.html"
        },                {
            "fqsen": "\\App\\Twig",
            "name": "Twig",
            "summary": "",
            "url": "namespaces/app-twig.html"
        }            ]
);
